# environement
env:
  # TERM terminal colors
  TERM: xterm-256color

window:
  dimensions:
    columns: 200
    lines: 60
  padding:
    x: 10
    y: 10
  decorations: buttonless
  opacity: 0.9

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  size: 16

draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/themes/hardhacker/hardhacker.yml 
