import = ["/Users/saiza/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.yml", "/Users/saiza/.config/alacritty/themes/tokyonight-night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 160
lines = 45

[window.padding]
x = 10
y = 10

[window.position]
x = 10
y = 10
